---

- name: Create the ~/.local/bin folder
  ansible.builtin.file:
    path: "{{ user_home + '/.local/bin' }}"
    state: directory
    mode: '0755'
  register: _result

- name: Find the tag for the latest version
  ansible.builtin.command: |
    curl -sL "https://api.github.com/repos/direnv/direnv/releases/latest"
  register: _result_direnv
  changed_when: false
  no_log: true

- name: Get tag_name
  ansible.builtin.set_fact:
    tag_name: "{{ (_result_direnv.stdout | from_json)['tag_name'] }}"

- name: Download the application
  ansible.builtin.get_url:
    url: "{{ 'https://github.com/direnv/direnv/releases/download/' + tag_name + '/direnv.' + os_family + '-' + cpu_arch }}"
    dest: "{{ user_home + '/.local/bin/direnv' }}"
    mode: '0755'

- name: Create the ~/.bashrc.d folder
  ansible.builtin.file:
    path: "{{ user_home + '/.bashrc.d' }}"
    state: directory
    mode: '0755'
  register: _result

- name: Create ~/.bashrc.d/direnv file
  ansible.builtin.copy:
    content: |
      eval "$(direnv hook bash)"
    dest: "{{ user_home + '/.bashrc.d/direnv.bash' }}"
    mode: '0644'
  register: _result

- name: Clear temporary facts
  ansible.builtin.set_fact:
    _result_direnv: {}
