---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

vars_host:
  local_storage_class: 'local-filesystem-storage'
  local_storage_namespace: 'local-storage'

  nfs_storage_class: nfs-filesystem-storage'
  nfs_storage_namespace: nfs-local-storage'
  nfs_provisioner: "{{ cluster_domain + '/nfs-provisioner' }}"
  nfslocal_storage_class: 'nfs-filesystem-storage'
  nfslocal_block_class: 'nfs-filesystem-storage'

  # Rook-ceph release from https://github.com/rook/rook/releases
  rook_ceph_release: 'v1.8.6'
  cephfs_device_filter: 'vdb'
  cephfs_storage_class: 'rook-cephfs'
  cephfs_block_class: 'rook-ceph-block'

  default_storage_class: ''
  default_block_class: ''
