---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

vars_host:
  cluster_description: 'Kubernetes Cluster'
  cluster_domain: 'home.arpa'
  cluster_name: ''
  cluster_provisioner: ''
  clusters_basedir: ''
  network_cidr: ''
  http_proxy: ''
  cluster_host_names: []
  single_node: false
  api_vip: ''
  ingress_vip: ''
  kubernetes_distro: ''
  openshift_distro: ''
  openshift_version: ''
  load_ssh_keypair: true
  templates_basedir: '/home/runner/.kube/clusters'
  autowas_archive_url: 'http://rtpgsa.ibm.com/gsa/rtpgsa/projects/m/moonstone/drivers/releases/latest.tar.gz'
  autowas_basedir: '/opt/autowas'
  autowas_config_dir: '/opt/scripts'
  autowas_config_file: 'default_v9_latest_2node.cfg'
  autowas_cfg_ssh_user: 'root'
  autowas_cfg_install_path_basedir: '/opt'
