---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

vars_host:
  cluster_operators_namespace: 'openshift-operators'
  cluster_operators_catalog_source_namespace: 'openshift-marketplace'

  community_operators_catalog_source_name: 'community-operators'
  community_operators_catalog_source_namespace: "{{ cluster_operators_catalog_source_namespace }}"

  certified_operators_catalog_source_name: 'certified-operators'
  certified_operators_catalog_source_namespace: "{{ cluster_operators_catalog_source_namespace }}"

  redhat_marketplace_catalog_source_name: 'redhat-marketplace'
  redhat_marketplace_catalog_source_namespace: "{{ cluster_operators_catalog_source_namespace }}"

  redhat_operators_catalog_source_name: 'redhat-operators'
  redhat_operators_catalog_source_namespace: "{{ cluster_operators_catalog_source_namespace }}"

  ibm_operator_catalog_source_name: 'ibm-operator-catalog'
  ibm_operator_catalog_source_namespace: "{{ cluster_operators_catalog_source_namespace }}"

  ibm_operator_catalog_source_display_name: 'IBM Operator Catalog'
  ibm_operator_catalog_source_image: 'icr.io/cpopen/ibm-operator-catalog'
  ibm_operator_catalog_source_image_tag: ''
  ibm_operator_catalog_source_publisher: 'IBM'
  ibm_operator_catalog_source_poll_interval: '45m'

cluster_operators_catalog_source_map:
  community-operators:
    name: "{{ community_operators_catalog_source_name }}"
    namespace: "{{ community_operators_catalog_source_namespace }}"
  certified-operators:
    name: "{{ certified_operators_catalog_source_name }}"
    namespace: "{{ certified_operators_catalog_source_namespace }}"
  redhat-marketplace:
    name: "{{ redhat_marketplace_catalog_source_name }}"
    namespace: "{{ redhat_marketplace_catalog_source_namespace }}"
  redhat-operators:
    name: "{{ redhat_operators_catalog_source_name }}"
    namespace: "{{ redhat_operators_catalog_source_namespace }}"
  ibm-operator-catalog:
    name: "{{ ibm_operator_catalog_source_name }}"
    namespace: "{{ ibm_operator_catalog_source_namespace }}"
