---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

provisioning_role: 'cluster_request_fyreocp'
deprovisioning_role: 'cluster_cleanup_fyreocp'
cluster_facts_role: 'cluster_gather_facts_fyreocp'

ssh_keypair_path_prefix: fyre_
ssh_keytype: ed25519

distro_provisioning_roles:
  k8s: cluster_request_fyre_k8s
  ocp: cluster_request_fyre_ocp
  openshift: cluster_request_fyre_ocp

# Fyre constants

fyre_apiurl: "https://api.fyre.ibm.com/rest/v1/"
fyre_clusterstatusurl: "{{ fyre_apiurl + '?operation=query&request=showclusterdetails&cluster_name=' + cluster_name }}"
fyre_opshowclusterurl: "{{ fyre_apiurl + '?operation=query&request=showclusters' }}"
fyre_clusterdeleteurl: "{{ fyre_apiurl + '?operation=delete' }}"

fyreocpplus_ocpavailableurl: "{{ 'https://ocpapi.svl.ibm.com/v1/ocp_available/' + fyre_platform }}"
fyreocpplus_ocpdeployurl: 'https://ocpapi.svl.ibm.com/v1/ocp/'
fyreocpplus_clusterstatusurl: "{{ fyreocpplus_ocpdeployurl + cluster_name }}"

ocpplus_check_hostname: "{{ 'https://ocpapi.svl.ibm.com/v1/check_hostname/' + cluster_name }}"

# Custom OCP cluster facts

rhcos_url_prefix: "{{ 'https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/' + rhcos_version_path + '/' }}"
rhcos_sha_url: "{{ rhcos_url_prefix + 'sha256sum.txt' }}"

clients_url_prefix: "{{ 'https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/' + ocp_version_path + '/' }}"
clients_sha_url: "{{ clients_url_prefix + 'sha256sum.txt' }}"

# Fyre parameters


# set nodes cpu and memory size based on cluster size
tshirt_sizes:
  s:
    cpu: 2
    memory: 2
  m:
    cpu: 2
    memory: 4
  l:
    cpu: 4
    memory: 8
  x:
    cpu: 8
    memory: 16
  xl:
    cpu: 16
    memory: 32

vars_host:
  fyre_ocptype: 'ocpplus'
  fyre_site: 'rtp'
  fyre_platform: 'x'
  fyre_group_id: 0
  fyre_force_basic_auth: true
  fyre_master_quantity: 3
  fyre_master_cpu: 8
  fyre_master_memory: 16
  fyre_worker_quantity: 3
  fyre_worker_cpu: 8
  fyre_worker_memory: 16
  fyre_worker_additional_disk: ['200']
  fyre_quickburn_size: 'medium'
  fyre_quickburn_ttl: 12
