---

ansible_host: localhost
ansible_connection: local
ansible_python_interpreter: "{{ ansible_playbook_python }}"

vars_host:
  container_secrets_dir: '/run/secrets'
  container_secrets_vars_dir: '/run/secrets'
  secrets_dir: "{{ (playbook_dir + '/../.secrets') | realpath }}"
  secrets_vars_dir: "{{ (playbook_dir + '/../secrets') | realpath }}"
