#
# Ansible requirements
#

---

collections:
  - name: ansible.posix
    version: '2.1.0'
  - name: community.general
    version: '11.2.1'
  - name: community.okd
    version: '4.0.2'
  - name: containers.podman
    version: '1.17.0'
  - name: kubernetes.core
    version: '5.4.0'
