#
# Ansible requirements
#

---

collections:
  - name: ansible.posix
    version: '1.5.4'
  - name: community.general
    version: '9.0.1'
  - name: community.okd
    version: '4.0.0'
  - name: containers.podman
    version: '1.15.1'
  - name: kubernetes.core
    version: '5.0.0'
