---

- name: Create map from cli_args extra_vars
  ansible.builtin.set_fact:
    extra_vars: "{{ extra_vars | default({}) | combine({item_key: item_value}, recursive=true) }}"
  loop: "{{ cli_args.extra_vars }}"
  vars:
    item_key: "{{ item | regex_replace('=.*','') }}"
    item_value: "{{ item | regex_replace('^[^=]*=','') }}"

- name: "Create map of all hosts declared using *host(s)_spec extra vars"
  ansible.builtin.set_fact:
    hosts_specs_map: "{{ hosts_specs_map | default({}) | combine(extra_vars[item]) }}"
  loop: "{{ extra_vars.keys() }}"
  when: item is match('.*hosts?_spec') and extra_vars[item] is mapping

- when: (hosts_specs_map | default({})).keys() | length > 0
  name: Parse hosts_specs_map when present
  ansible.builtin.include_tasks: parse_hosts_spec.yml

- name: "Create map of all groups declared using *group(s)_spec extra vars"
  ansible.builtin.set_fact:
    groups_specs_map: "{{ groups_specs_map | default({}) | combine(extra_vars[item]) }}"
  loop: "{{ extra_vars.keys() }}"
  when: item is match('.*groups?_spec') and extra_vars[item] is mapping

- when: (groups_specs_map | default({})).keys() | length > 0
  name: Parse groups_specs_map when present
  ansible.builtin.include_tasks: parse_groups_spec.yml
