---

- when: inventory_hostname == (groups['all_nodes'] | first)
  name: Tasks which are only performed on the first VM
  block:

    - name: Install tWAS server
      ansible.builtin.shell:
        chdir: /opt/scripts
        cmd: source /opt/autowas/bin/AutoWASEnv.sh && cfg -cfg default_v9_latest_2node.cfg install && touch /opt/scripts/.install_completed
        creates: /opt/scripts/.install_completed
        executable: /bin/bash
      register: _result
      changed_when: _result.start != None

    - name: Create tWAS server topology
      ansible.builtin.shell:
        chdir: /opt/scripts
        cmd: source /opt/autowas/bin/AutoWASEnv.sh && cfg -cfg default_v9_latest_2node.cfg createTopology && touch /opt/scripts/.createTopology_completed
        creates: /opt/scripts/.createTopology_completed
        executable: /bin/bash
      register: _result
      changed_when: _result.start != None
