---

- name: Register our cluster with the assisted-install service
  ansible.builtin.set_fact:
    cluster_name: "{{ hostvars['cluster-facts'].options.cluster_name }}"
    openshift_version: "{{ hostvars['cluster-facts'].openshift_version }}"
    cluster_domain: "{{ hostvars['cluster-facts'].options.cluster_domain }}"
    http_proxy: "{{ hostvars['cluster-facts']['http_proxy'] }}"
    network_cidr: "{{ hostvars['cluster-facts']['network_cidr'] }}"
    single_node: "{{ hostvars['cluster-facts']['single_node'] }}"
    api_vip: "{{ hostvars['cluster-facts']['api_vip'] if not hostvars['cluster-facts']['single_node'] else omit }}"
    ingress_vip: "{{ hostvars['cluster-facts']['ingress_vip'] if not hostvars['cluster-facts']['single_node'] else omit }}"

- name: Set secret facts used in this role
  ansible.builtin.set_fact:
    _secrets:
      openshift_pullsecret: "{{ openshift_pullsecret }}"
      ssh_public_key: "{{ ssh_public_key }}"
  vars:
    secrets: "{{ hostvars['playbook-secrets'].secrets }}"
    openshift_pullsecret_secret: "{{ secrets.openshift_pullsecret }}"
    ssh_public_key_secret: "{{ secrets.ssh_public_key }}"
    openshift_pullsecret: "{{ lookup(openshift_pullsecret_secret.module, openshift_pullsecret_secret.param) | trim }}"
    ssh_public_key: "{{ lookup(ssh_public_key_secret.module, ssh_public_key_secret.param) | trim }}"
  no_log: true

- name: Get a list of the cluster objects
  ansible.builtin.uri:
    url: "{{ assisted_install_rest_url }}/clusters"
  register: _result

- name: See if a cluster already exists with our name
  ansible.builtin.set_fact:
    cluster_id: "{{ item.id }}"
  loop: "{{ _result.json }}"
  when: item.name == cluster_name

# TODO: Compare fields against the values we would use to create the cluster

- when: cluster_id | default('') | length == 0
  name: Register the cluster with the service
  block:

    - name: Set facts to register cluster
      ansible.builtin.set_fact:
        high_availability_mode: "{{ ('None' if (single_node) else 'Full') | string }}"

    - name: Register our cluster
      ansible.builtin.uri:
        url: "{{ assisted_install_rest_url }}/clusters"
        method: POST
        body_format: json
        body:
          name: "{{ cluster_name }}"
          openshift_version: "{{ openshift_version }}"
          pull_secret: "{{ _secrets.openshift_pullsecret | string }}"
          high_availability_mode: "{{ high_availability_mode }}"
          base_dns_domain: "{{ cluster_domain }}"
          ssh_public_key: "{{ _secrets.ssh_public_key }}"
          http_proxy: "{{ http_proxy }}"
          network_type: "{{ 'OVNKubernetes' if (single_node) else 'OpenShiftSDN' }}"
          machine_networks:
          - cidr: "{{ network_cidr }}"
          api_vip: "{{ api_vip | default(omit) }}"
          ingress_vip: "{{ ingress_vip | default(omit) }}"
          vip_dhcp_allocation: false
          schedulable_masters: true
          additional_ntp_source: 'ns-gce.sslip.io,time.cloudflare.com'
        status_code: 201
      register: _result

    - name: Set cluster id
      ansible.builtin.set_fact:
        cluster_id: "{{ _result.json.id }}"

    - name: Remove previous cluster dir
      ansible.builtin.file:
        path: "{{ cluster_dir }}"
        state: absent

- name: Get a list of the infra-env objects
  ansible.builtin.uri:
    url: "{{ assisted_install_rest_url }}/infra-envs"
  register: _result

- name: See if our infra-env already exists
  ansible.builtin.set_fact:
    infra_env_id: "{{ item.id }}"
  loop: "{{ _result.json }}"
  when: item.name == (cluster_name + '_infra-env')

- name: Register infra-env for our cluster
  ansible.builtin.uri:
    url: "{{ assisted_install_rest_url }}/infra-envs"
    method: POST
    body_format: json
    body:
      name: "{{ cluster_name }}_infra-env"
      cluster_id: "{{ cluster_id }}"
      openshift_version: "{{ openshift_version }}"
      proxy:
        http_proxy: "{{ http_proxy }}"
        no_proxy: ""
      pull_secret: "{{ _secrets.openshift_pullsecret | string }}"
      ssh_authorized_key: "{{ _secrets.ssh_public_key }}"
    status_code: 201
  register: _result
  when: infra_env_id | default('') | length == 0

- name: Clear _secrets fact
  ansible.builtin.set_fact:
    _secrets: {}

- name: Check to see if we were asked to stop here
  ansible.builtin.include_role:
    name: check_stop_after
  vars:
    task_to_check: assisted-register-cluster

- name: Gather assisted cluster facts
  ansible.builtin.include_role:
    name: cluster_gather_facts_assisted
  vars:
    cluster_facts_only: true

- name: Collect ipxe macaddrs from all cluster hosts
  ansible.builtin.set_fact:
    cluster_ipxe_macaddrs: "{{ (cluster_ipxe_macaddrs | default([])) + [item] }}"
  loop: "{{ hostvars['cluster-facts']['cluster_host_names'] | map('extract', hostvars, 'ipxe_mac_address') }}"

- name: Create ipxe folders for cluster host mac addresses
  ansible.builtin.file:
    path: "{{ services_dir + '/ipxe/' + item }}"
    state: directory
    mode: '0755'
  loop: "{{ cluster_ipxe_macaddrs }}"
  register: _result

- name: Create the boot.ipxe file
  ansible.builtin.get_url:
    url: "{{ infra_env_url }}/downloads/files?file_name=ipxe-script&mac={{ item }}"
    dest: "{{ services_dir + '/ipxe/' + item + '/boot.ipxe' }}"
    mode: '0644'
  register: _result
  changed_when: false
  loop: "{{ cluster_ipxe_macaddrs }}"

- name: Wait until the image download service is ready
  ansible.builtin.uri:
    url: "http://{{ hostvars['localhost-facts']['address_on_cluster_network'] }}:8888/health"
  register: _result
  delay: 30
  retries: 10
  until: _result is defined and _result.status == 200

- name: Boot the cluster hosts
  ansible.builtin.include_role:
    name: power_on_cluster_hosts
  vars:
    cluster_host_names: "{{ hostvars['cluster-facts'].cluster_host_names }}"
    secrets: "{{ hostvars['playbook-secrets'].secrets }}"
    ipmitool_username_secret: "{{ secrets.ipmitool_username }}"
    ipmitool_password_secret: "{{ secrets.ipmitool_password }}"
    ipmitool_username: "{{ lookup(ipmitool_username_secret.module, ipmitool_username_secret.param) }}"
    ipmitool_password: "{{ lookup(ipmitool_password_secret.module, ipmitool_password_secret.param) }}"
    ipmitool_username_value: "{{ ipmitool_username_secret.value | b64decode }}"
    ipmitool_password_value: "{{ ipmitool_password_secret.value | b64decode }}"

- name: Wait for all cluster hosts entries to appear in the infra-env
  ansible.builtin.uri:
    url: "{{ infra_env_url }}/hosts"
  register: _result
  delay: 30
  retries: 20
  until: >
    (_result.status == 200 and _result.json | length > 0) and
    (_result.json | map(attribute='inventory', default='MISSING') | intersect(['MISSING']) | length == 0) and
    (_result.json | map(attribute='inventory') | length == groups['cluster_hosts'] | length)

- name: Set host facts
  ansible.builtin.set_fact:
    host_id: "{{ item.id }}"
    host_inventory: "{{ item.inventory | from_json }}"
    host_url: "{{ assisted_install_host_url }}{{ item.href }}"
  loop: "{{ _result.json }}"
  delegate_to: "{{ item.requested_hostname }}"
  delegate_facts: true

- name: Set host hostname fact
  ansible.builtin.set_fact:
    host_hostname: "{{ hostvars[item]['host_inventory']['hostname'] }}"
  loop: "{{ groups['cluster_hosts'] }}"
  delegate_to: "{{ item}}"
  delegate_facts: true

- name: Wait for hosts to enter known state or beyond
  ansible.builtin.uri:
    url: "{{ hostvars[item]['host_url'] }}"
  loop: "{{ groups['cluster_hosts'] }}"
  register: _result
  delay: 30
  retries: 20
  until: _result.status == 200 and _result.json.status in ['known', 'installing-in-progress', 'installed']

- name: Fetch current hosts status
  ansible.builtin.uri:
    url: "{{ hostvars[item]['host_url'] }}"
  loop: "{{ groups['cluster_hosts'] }}"
  register: _result

- name: Wait for hosts to enter ready to install state
  ansible.builtin.uri:
    url: "{{ hostvars[item]['host_url'] }}"
  loop: "{{ groups['cluster_hosts'] }}"
  register: _result
  delay: 30
  retries: 20
  until: _result.json.status in ['known', 'installing-in-progress', 'installed']

- name: Collect the host status of all cluster hosts
  ansible.builtin.set_fact:
    all_host_states: "{{ _result.results | map(attribute='json.status') | unique }}"

- when: (['known'] is subset(all_host_states))
  name: Select the install disk
  block:

    - name: Collect the install disk id on all cluster hosts
      ansible.builtin.set_fact:
        cluster_install_disks: "{{ cluster_install_disks | default([]) + ([hostname] | product(paths)) }}"
      loop: "{{ groups['cluster_hosts'] | zip(groups['cluster_hosts'] | map('extract', hostvars, 'host_inventory') | map(attribute='disks')) }}"
      vars:
        hostname: "{{ item[0] }}"
        paths: "{{ item[1] | map(attribute='name') | zip(item[1] | map(attribute='id')) }}"

    - name: Select our installation disk
      ansible.builtin.uri:
        url: "{{ host_url }}"
        method: PATCH
        body_format: json
        body:
          disks_selected_config:
          - id: "{{ install_disk_id }}"
            role: install
        status_code: 201
      loop: "{{ cluster_install_disks }}"
      vars:
        host_url: "{{ hostvars[item[0]]['host_url'] }}"
        disk_name: "{{ item[1][0] }}"
        install_disk_id: "{{ item[1][1] }}"
      register: _result
      when: disk_name == hostvars[item[0]]['install_disk']

- name: Set ssh_user fact
  ansible.builtin.set_fact:
    ssh_user: core

- name: Wait for hosts to enter ready to install state
  ansible.builtin.uri:
    url: "{{ hostvars[item]['host_url'] }}"
  loop: "{{ groups['cluster_hosts'] }}"
  register: _result
  delay: 30
  retries: 20
  until: _result.json.status in ['known', 'installing-in-progress', 'installed']

- name: Collect the host status of all cluster hosts
  ansible.builtin.set_fact:
    all_host_states: "{{ _result.results | map(attribute='json.status') | unique }}"

- when: (['known'] is subset(all_host_states))
  name: Clean all the disks
  block:

    - name: Collect the paths and eligibility of all disks on all cluster hosts
      ansible.builtin.set_fact:
        cluster_disks: "{{ cluster_disks | default([]) | union([ssh_host] | product(paths)) }}"
      loop: "{{ groups['cluster_hosts'] | zip(groups['cluster_hosts'] | map('extract', hostvars, 'host_inventory') | map(attribute='disks')) }}"
      vars:
        ssh_host: "{{ item[0] + '.' + hostvars[item[0]]['host_domain'] }}"
        paths: "{{ item[1] | map(attribute='path') | zip(item[1] | map(attribute='installation_eligibility.eligible', default=false)) }}"

    - name: Find eligible disks
      ansible.builtin.set_fact:
        eligible_disks: "{{ eligible_disks | default([]) | union([[ssh_host, path]]) }}"
      loop: "{{ cluster_disks }}"
      vars:
        ssh_host: "{{ item[0] }}"
        path: "{{ item[1][0] }}"
        eligible: "{{ item[1][1] }}"
      when: eligible

    - name: Find eligible hosts
      ansible.builtin.set_fact:
        eligible_hosts: "{{ eligible_hosts | default([]) | union([ssh_host]) }}"
      loop: "{{ eligible_disks }}"
      vars:
        ssh_host: "{{ item[0] }}"

    - name: Run ssh to find any lvm partitions
      ansible.builtin.command:
        ssh {{ ssh_user }}@{{ ssh_host }} sudo pvdisplay -C -o pv_name,vg_name --no-headings --separator ':'
      loop: "{{ eligible_hosts }}"
      vars:
        ssh_host: "{{ item }}"
      register: _result
      changed_when: _result is not defined

    - name: Create a list of all the pv/vg names
      ansible.builtin.set_fact:
        pv_vg_names: "{{ pv_vg_names | default([]) | union(entries) }}"
      loop: "{{ _result.results | map(attribute='item') | zip(_result.results | map(attribute='stdout_lines')) }}"
      vars:
        entries: "{{ [item[0]] | product(item[1]) }}"
      when: item[1] | length > 0

    - when: pv_vg_names | default([]) | length > 0
      name: Remove lvm volumes from any of our eligible disks
      block:

      - name: Create a list of the pvs/vgs to check
        ansible.builtin.set_fact:
          pv_vg_to_check: "{{ pv_vg_to_check | default([]) | union([{'host': ssh_host, 'pv': pv_name, 'vg': vg_name}]) }}"
        loop: "{{ pv_vg_names }}"
        vars:
          ssh_host: "{{ item[0] }}"
          pv_name: "{{ item[1] | trim | split(':') | first }}"
          vg_name: "{{ item[1] | trim | split(':') | last }}"

      - name: Create a list of the pvs/vgs to remove
        ansible.builtin.set_fact:
          pv_vg_to_remove: "{{ pv_vg_to_remove | default([]) | union(matching_pvs) }}"
        loop: "{{ eligible_disks }}"
        vars:
          matching_pvs: "{{ pv_vg_to_check | selectattr('host','==',item[0]) | selectattr('pv','match','^' + item[1]) }}"
        when: matching_pvs | length > 0

      - name: Run ssh to remove any lvm volume groups
        ansible.builtin.command:
          ssh {{ ssh_user }}@{{ ssh_host }} sudo vgremove -f {{ vg_name }}
        loop: "{{ pv_vg_to_remove }}"
        vars:
          ssh_host: "{{ item['host'] }}"
          vg_name: "{{ item['vg'] }}"
        register: _result
        changed_when: _result is not defined
        when: vg_name | length > 0

      - name: Run ssh to remove lvm physical volumes
        ansible.builtin.command:
          ssh {{ ssh_user }}@{{ ssh_host }} sudo pvremove -f {{ pv_name }}
        loop: "{{ pv_vg_to_remove }}"
        vars:
          ssh_host: "{{ item['host'] }}"
          pv_name: "{{ item['pv'] }}"
        register: _result
        changed_when: _result is not defined
        when: pv_name | length > 0

    - name: Run ssh to wipe the filesystems of all eligible disks
      ansible.builtin.command:
        ssh {{ ssh_user }}@{{ ssh_host }} sudo wipefs -a {{ path }}
      loop: "{{ eligible_disks }}"
      vars:
        ssh_host: "{{ item[0] }}"
        path: "{{ item[1] }}"
      register: _result
      changed_when: _result is not defined

    - name: Run ssh to wipe the filesystems of all eligible disks
      ansible.builtin.command:
        ssh {{ ssh_user }}@{{ ssh_host }} sudo dd if=/dev/zero of={{ path }}  bs=1M count=10 conv=fsync
      loop: "{{ eligible_disks }}"
      vars:
        ssh_host: "{{ item[0] }}"
        path: "{{ item[1] }}"
      register: _result
      changed_when: _result is not defined

    - name: Run ssh to show status of all disks
      ansible.builtin.command:
        ssh {{ ssh_user }}@{{ ssh_host }} sudo lsblk
      loop: "{{ eligible_hosts }}"
      vars:
        ssh_host: "{{ item }}"
      register: _result
      changed_when: _result is not defined

- name: Gather the host facts
  ansible.builtin.include_role:
    name: assisted_gather_hosts_facts
  vars:
    cluster_name: "{{ hostvars['cluster-facts'].options.cluster_name }}"

- name: Check to see if we should stop now
  ansible.builtin.include_role:
    name: check_stop_after
  vars:
    task_to_check: assisted-register-hosts

- name: Wait for hosts to enter ready to install state
  ansible.builtin.uri:
    url: "{{ hostvars[item]['host_url'] }}"
  loop: "{{ groups['cluster_hosts'] }}"
  register: _result
  delay: 30
  retries: 20
  until: _result.json.status in ['known', 'installing-in-progress', 'installed']

- name: Collect the host status of all cluster hosts
  ansible.builtin.set_fact:
    all_host_states: "{{ _result.results | map(attribute='json.status') | unique }}"

- when: all_host_states is subset(['known'])
  name: Take a snapshot of the cluster events
  block:

    - name: Create the cluster directory
      ansible.builtin.file:
        path: "{{ cluster_dir }}"
        state: directory
        mode: '0755'

    - name: Get the existing cluster events from before the install
      ansible.builtin.uri:
        url: "{{ hostvars['assisted-install']['cluster_events_url'] }}"
      register: _result

    - name: Copy cluster events to cluster_dir
      ansible.builtin.copy:
        content: "{{ _result.json | to_nice_json }}"
        dest: "{{ cluster_dir }}/cluster_events.json"
        mode: '0644'

    - name: Get a list of the cluster objects
      ansible.builtin.uri:
        url: "{{ hostvars['assisted-install']['cluster_url'] }}"
      register: _result

    - name: Copy cluster status to cluster_dir
      ansible.builtin.copy:
        content: "{{ _result.json | to_nice_json }}"
        dest: "{{ cluster_dir }}/cluster_status.json"
        mode: '0644'

    - name: Install cluster
      ansible.builtin.uri:
        url: "{{ hostvars['assisted-install']['cluster_url'] }}/actions/install"
        method: POST
        status_code: 202
      register: _result

- name: Wait for the cluster install to complete
  ansible.builtin.include_role:
    name: assisted_wait_for_install_complete
  vars:
    cluster_dir: "{{ hostvars['cluster-facts']['cluster_dir'] }}"
