---

- name: Install buildah if required
  ansible.builtin.package:
    name:
    - buildah
    - podman
    - skopeo
    state: present

- name: Allow services to linger
  ansible.builtin.include_role:
    name: 'services_enable_linger'

- name: Install infra host credentials
  ansible.builtin.include_role:
    name: 'infra_install_creds'

- name: Install container registry on infra host
  ansible.builtin.include_role:
    name: 'infra_install_registry'

- name: Install a registry proxy on infra host
  ansible.builtin.include_role:
    name: 'infra_install_registry_proxy'

- name: Install haproxy on infra host
  ansible.builtin.include_role:
    name: 'infra_install_haproxy'
