---

- name: Make sure directory exists
  ansible.builtin.file:
    path: '/etc/sudoers.d'
    state: 'directory'
    mode: '0750'
  become: true
  become_user: root

- name: Create new file allowing user to run sudo without a password
  ansible.builtin.copy:
    content: |
      {{ _user_name }}	ALL=(ALL) 	NOPASSWD: ALL
    dest: "{{ '/etc/sudoers.d/' + _user_name }}"
    mode: '0440'
  become: true
  become_user: root
  vars:
    _user_name: "{{ params.user_name }}"
