---

- name: "{{ 'Stop before ' + task_to_check + ' has started' }}"
  ansible.builtin.assert:
    that: (stop_before_task | default('')) != task_to_check
    msg: "{{ 'Stopping before ' + (stop_before_task | default('undefined task')) + ' has started' }}"
  tags: omit_from_grapher
