---

- when: inventory_hostname == (groups['all_nodes'] | first)
  name: Tasks which are only performed on the first VM
  block:

    - name: Uninstall tWAS server
      ansible.builtin.shell:
        chdir: /opt/scripts
        cmd: source /opt/autowas/bin/AutoWASEnv.sh && cfg -cfg default_v9_latest_2node.cfg force_uninstall && rm -f /opt/scripts/.install_completed /opt/scripts/.createTopology_completed
        executable: /bin/bash
      removes: /opt/scripts/.install_completed
      register: _result
      changed_when: _result.start != None
