---

- when: inventory_hostname == (groups['all_nodes'] | first)
  name: Tasks which are only performed on the first VM
  block:

    - name: Uninstall tWAS server
      ansible.builtin.shell:
        chdir: "{{ autowas_config_dir }}"
        cmd: source {{ autowas_env_script }} && cfg -cfg {{ autowas_config_file }} force_uninstall && rm -f {{ install_marker }} {{ topology_marker }} {{ bootstrap_marker }}
        executable: /bin/bash
        removes: "{{ install_marker }}"
      register: _result
      changed_when: _result.start != None

  vars:
    autowas_basedir: "{{ hostvars['cluster-facts'].options.autowas_basedir }}"
    autowas_config_dir: "{{ hostvars['cluster-facts'].options.autowas_config_dir }}"
    autowas_config_file: "{{ hostvars['cluster-facts'].options.autowas_config_file }}"
    autowas_env_script: "{{ autowas_basedir + '/bin/AutoWASEnv.sh' }}"
    install_marker: "{{ autowas_config_dir + '/.install_completed' }}"
    topology_marker: "{{ autowas_config_dir + '/.createTopology_completed' }}"
    bootstrap_marker: "{{ autowas_config_dir + '/.generateBootstrap_completed' }}"
