---

- when: inventory_hostname == (groups['all_nodes'] | first)
  name: Tasks which are only performed on the first VM
  block:

    - name: Nuke tWAS server processes
      ansible.builtin.shell:
        chdir: "{{ autowas_config_dir }}"
        cmd: source {{ autowas_env_script }} && cfg nuke
        executable: /bin/bash
      register: _result
      changed_when: _result.start != None

    - name: Uninstall tWAS server
      ansible.builtin.shell:
        chdir: "{{ autowas_config_dir }}"
        cmd: source {{ autowas_env_script }} && cfg force_uninstall && rm -f {{ install_marker }} {{ topology_marker }} {{ bootstrap_marker }}
        executable: /bin/bash
      register: _result
      changed_when: _result.start != None

    - name: Create the ~/.cache/autowas folder
      ansible.builtin.file:
        path: "{{ user_home + '/.cache/autowas' }}"
        state: directory
        mode: '0755'
      register: _result

    - name: Archive the contents of the autowas_config_dir
      community.general.archive:
        dest: "{{ user_home + '/.cache/autowas/saved-' + now(fmt='%Y-%m-%dT%H:%M:%S') + '.tar.gz' }}"
        mode: '0644'
        path: "{{ autowas_config_dir }}"
        exclusion_patterns:
          - 'scripts/regression/tools/*'

    - name: Remove the autowas_config_dir folder
      ansible.builtin.file:
        path: "{{ autowas_config_dir }}"
        state: absent
      register: _result

  vars:
    autowas_basedir: "{{ hostvars['autowas-facts'].options.autowas_basedir }}"
    autowas_config_dir: "{{ hostvars['autowas-facts'].options.autowas_config_dir }}"
    autowas_config_file: "{{ hostvars['autowas-facts'].options.autowas_config_file }}"
    autowas_env_script: "{{ autowas_basedir + '/bin/AutoWASEnv.sh' }}"
    install_marker: "{{ autowas_config_dir + '/.install_completed' }}"
    topology_marker: "{{ autowas_config_dir + '/.createTopology_completed' }}"
    bootstrap_marker: "{{ autowas_config_dir + '/.generateBootstrap_completed' }}"

- name: Remove other folders created by install_twas role
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ autowas_cfg_install_path_basedir + '/.ibm' }}"
    - '/etc/.ibm'
    - '/tmp/autowas/buildcache'
  register: _result
  vars:
    autowas_cfg_install_path_basedir: "{{ hostvars['autowas-facts'].options.autowas_cfg_install_path_basedir }}"
