---

- name: This needs to be debugged
  ansible.builtin.fail:
    msg: 'this code needs to be updated'

- name: Set of assertions for kubernetes clusters
  ansible.builtin.assert:
    that:
    - options.fyredev_bastion_count == bastion_count
    - options.fyredev_master_count in [1, 3, 5]
    - options.fyredev_worker_count | int >= 0
  vars:
    bastion_count: "{{ 0 if options.fyredev_master_count == 1 else 1 }}"

- when: options.fyredev_group_id == 0
  name: Lookup group id from quota
  block:

    - name: Lookup the quota available to us
      ansible.builtin.uri:
        url: "{{ fyreocp_quotaurl }}"
        method: GET
        user: "{{ _secrets.fyre_user }}"
        password: "{{ _secrets.fyre_apikey }}"
        validate_certs: false
        force_basic_auth: "{{ options.fyredev_force_basic_auth }}"
      changed_when: false
      register: _result_user_quota

    - name: Set _fyredev_group_id fact
      ansible.builtin.set_fact:
        _fyredev_group_id: "{{ _result_user_quota.json.details | map(attribute='product_group_id') | first | int }}"

- name: Wait until we have enough quota for the request
  ansible.builtin.uri:
    url: "{{ fyredev_getquotaurl }}"
    method: GET
    user: "{{ _secrets.fyre_user }}"
    password: "{{ _secrets.fyre_apikey }}"
    validate_certs: false
    force_basic_auth: "{{ options.fyredev_force_basic_auth }}"
  register: _result_user_quota
  changed_when: false
  vars:
    bastion_mem: "{{ (options.fyredev_bastion_count | int) * (options.fyredev_bastion_mem | int) }}"
    master_mem: "{{ (options.fyredev_master_count | int) * (options.fyredev_master_mem | int) }}"
    worker_mem: "{{ (options.fyredev_worker_count | int) * (options.fyredev_worker_mem | int) }}"
    cluster_mem_needed: "{{ bastion_mem + master_mem + worker_mem }}"
    cluster_mem_available: "{{ (_result_user_quota.json.memory_quota_gb | int) - (_result_user_quota.json.memory_allocated_gb | int) }}"
    fyredev_group_id: "{{ _fyredev_group_id | default(options.fyredev_group_id) }}"
    fyredev_user_email: "{{ _secrets.fyre_user_email }}"
  delay: 20
  retries: 30
  until: cluster_mem_available >= cluster_mem_needed

- name: Ensure empty cluster dir
  ansible.builtin.file:
    path: "{{ cluster_dir }}"
    mode: '0755'
    state: "{{ item }}"
  loop:
  - absent
  - directory

- name: Write cluster specific fyre request body
  ansible.builtin.copy:
    content: |
      fyre:
        creds:
          username: {{ _secrets.fyre_user }}
          api_key: {{ _secrets.fyre_apikey }}
          public_key: {{ hostvars['cluster-facts'].options.ssh_public_key }}
      product_group_id: {{ _fyredev_group_id | default(options.fyredev_group_id) }}
      cluster_prefix: {{ cluster_name }}
      clusterconfig:
        instance_type: 'virtual_server'
        platform: {{ options.fyredev_platform }}
        user_comment: "{{ 'kubernetes cluster of ' + _secrets.fyre_user }}"
      site: {{ options.fyredev_site }}
      {{ cluster_name }}:
      {% if options.fyredev_bastion_count == 1 %}
        - name: '{{ options.fyredev_bastion_name | string }}'
          cpu: {{ options.fyredev_bastion_cpu }}
          memory: {{ options.fyredev_bastion_mem }}
          os: '{{ options.fyredev_bastion_os }}'
          publicvlan: 'y'
          privatevlan: 'y'
      {% if options.fyredev_bastion_additional_disks | default([]) | length > 0 %}
          additional_disks: {{ options.fyredev_bastion_additional_disks }}
      {% endif %}
      {% endif %}
      {% if options.fyredev_master_count == 1 %}
        - name: 'master'
          cpu: {{ options.fyredev_master_cpu }}
          memory: {{ options.fyredev_master_mem }}
          os: '{{ options.fyredev_node_os }}'
          publicvlan: {{ 'n' if options.fyredev_bastion_count == 1 else 'y' }}
          privatevlan: 'y'
      {% if options.fyredev_master_additional_disks | default([]) | length > 0 %}
          additional_disks: {{ options.fyredev_bastion_additional_disks }}
      {% endif %}
      {% else %}
      {% for index in range(0, options.fyredev_master_count | int) %}
        - name: "{{ 'master' + index | string }}"
          cpu: {{ options.fyredev_master_cpu }}
          memory: {{ options.fyredev_master_mem }}
          os: '{{ options.fyredev_node_os }}'
          publicvlan: 'n'
          privatevlan: 'y'
      {% if options.fyredev_master_additional_disks | default([]) | length > 0 %}
          additional_disks: {{ options.fyredev_bastion_additional_disks }}
      {% endif %}
      {% endfor %}
      {% endif %}
      {% for index in range(0, options.fyredev_worker_count | int) %}
        - name: "{{ 'worker' + index | string }}"
          cpu: {{ options.fyredev_worker_cpu }}
          memory: {{ options.fyredev_worker_mem }}
          os: '{{ options.fyredev_node_os }}'
          publicvlan: 'n'
          privatevlan: 'y'
      {% if options.fyredev_worker_additional_disks | default([]) | length > 0 %}
          additional_disks: {{ options.fyredev_bastion_additional_disks }}
      {% endif %}
      {% endfor %}
    dest: "{{ cluster_dir + '/fyredev_build_req.yml' }}"
    mode: '0600'

- name: Clear register results and temporary facts
  ansible.builtin.set_fact:
    _fyredev_group_id: 0
    _result_user_quota: {}
