---

- name: Add keypair to authorized_keys on inventory_hostname
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ ssh_pubkey }}"
    comment: "{{ ssh_comment }}"
    state: present
  become: "{{ ssh_become_user | default('') | length > 0 }}"
  become_user: "{{ ssh_become_user | default(omit) }}"
  vars:
    ssh_user: "{{ params.remote_user | default(hostvars['playbook-facts'].remote_user) }}"
    ssh_pubkey: "{{ hostvars['playbook-facts'].authorized_keys[params.authorized_key_name].pubkey }}"
    ssh_comment: "{{ hostvars['playbook-facts'].authorized_keys[params.authorized_key_name].comment }}"
    ssh_become_user: "{{ params.become_user | default('root') }}"
