---

- name: Gather facts
  ansible.builtin.setup:
    filter:
    - 'ansible_architecture'
    - 'ansible_distribution'
    - 'ansible_env'
    - 'ansible_os_family'
    - 'ansible_user_dir'
    - 'ansible_user_id'
    gather_subset:
    - '!all'
    - 'network'

- name: Clear ansible_facts
  ansible.builtin.set_fact:
    ansible_facts: {}

- name: Set derived localhost facts
  ansible.builtin.set_fact:
    cpu_arch: "{{ 'amd64' if (ansible_architecture == 'x86_64') else ansible_architecture }}"
    os_family: "{{ 'mac' if (ansible_os_family == 'Darwin') else ('windows' if (ansible_os_family == 'Windows') else 'linux') }}"
    local_path: "{{ ansible_env['PATH'] }}"
    local_home: "{{ ansible_user_dir }}"
    local_user: "{{ ansible_user_id }}"

- when: localhost_spec is defined
  name: Process localhost_spec
  block:

  - name: Load localhost_spec from cli param into a dictionary
    ansible.builtin.set_fact:
      localhost_map: "{{ localhost_spec | from_json }}"

  - name: Set facts from localhost_spec
    ansible.builtin.set_fact:
      "{{ item }}": "{{ localhost_map[item] }}"
    loop: "{{ localhost_map.keys() | default([]) }}"

# - name: Set ssh_keypair_name derived facts
#   set_fact:
#     ssh_keypair_path: "{{ local_home + '/.ssh/' + ssh_keypairs[ssh_keypair_name].path_prefix + 'id_' + ssh_keytype }}"
#     ssh_keypair_secret: "{{ ssh_keypairs[ssh_keypair_name].secret }}"
#   when: ssh_keypair_name is defined
