---

- name: Download the archive to a temporary file
  ansible.builtin.get_url:
    url: "{{ zipper + '/prebuild.zip' }}"
    dest: "{{ wasbld_folder + '/prebuild.zip.tmp' }}"
    force_basic_auth: true
    url_username: "{{ gsa_username }}"
    url_password: "{{ gsa_password }}"
    validate_certs: false
    mode: '0644'
  vars:
    secrets: "{{ hostvars['playbook-secrets'].secrets }}"
    gsa_username_secret: "{{ secrets.gsa_username }}"
    gsa_password_secret: "{{ secrets.gsa_password }}"
    gsa_username: "{{ lookup(gsa_username_secret.module, gsa_username_secret.param) | trim }}"
    gsa_password: "{{ lookup(gsa_password_secret.module, gsa_password_secret.param) | trim }}"
  register: _result

- name: Move the temporary file to the correct name
  ansible.builtin.command:
    cmd: mv prebuild.zip.tmp prebuild.zip
    chdir: "{{ wasbld_folder }}"
  register: _result
  changed_when: _result.rc == 0

- name: Extract the prebuild files
  ansible.builtin.unarchive:
    src: "{{ wasbld_folder + '/prebuild.zip' }}"
    dest: "{{ wasbld_folder }}"
    extra_opts: ['-q']
    remote_src: true
  no_log: true
  register: _result

- name: Print out the result
  ansible.builtin.debug: msg="{{ _result | combine(empty_diff) }}"
  vars:
    empty_diff:
      diff: {}

- name: Create the marker after prebuild archive has been unzipped
  ansible.builtin.file:
    path: "{{ wasbld_folder + '/.prebuildunzipped' }}"
    state: touch
    mode: '0644'
  register: _result
