---

- name: Download the archive to a temporary file
  ansible.builtin.get_url:
    url: "{{ zipper + '/linux_java.zip' }}"
    dest: "{{ wasbld_folder + '/linux_java.zip.tmp' }}"
    force_basic_auth: true
    url_username: "{{ gsa_username }}"
    url_password: "{{ gsa_password }}"
    validate_certs: false
    mode: '0644'
  vars:
    secrets: "{{ hostvars['playbook-secrets'].secrets }}"
    gsa_username_secret: "{{ secrets.gsa_username }}"
    gsa_password_secret: "{{ secrets.gsa_password }}"
    gsa_username: "{{ lookup(gsa_username_secret.module, gsa_username_secret.param) | trim }}"
    gsa_password: "{{ lookup(gsa_password_secret.module, gsa_password_secret.param) | trim }}"
  register: _result

- name: Move the temporary file to the correct name
  ansible.builtin.command:
    cmd: mv linux_java.zip.tmp linux_java.zip
    chdir: "{{ wasbld_folder }}"
  register: _result
  changed_when: _result.rc == 0

- name: Create the temporary folder to extract java files into
  ansible.builtin.file:
    path: "{{ wasbld_folder + '/java-tmp' }}"
    state: directory
    mode: '0755'
  register: _result

- name: Extract the java files
  ansible.builtin.unarchive:
    src: "{{ wasbld_folder + '/linux_java.zip' }}"
    dest: "{{ wasbld_folder + '/java-tmp' }}"
    extra_opts: ['-q']
    include: 'java/linuxamd64/*'
    remote_src: true
  no_log: true
  register: _result

- name: Print out the result
  ansible.builtin.debug: msg="{{ _result | combine(empty_diff) }}"
  vars:
    empty_diff:
      diff: {}

- name: Remove the target java folder
  ansible.builtin.file:
    path: "{{ wasbld_folder + '/java' }}"
    state: absent
  register: _result

- name: Move the extracted files to where we really want them
  ansible.builtin.command:
    cmd: mv java-tmp/java/linuxamd64 java
    chdir: "{{ wasbld_folder }}"
  register: _result
  changed_when: _result.rc == 0

- name: Remove the temporary java download folder
  ansible.builtin.file:
    path: "{{ wasbld_folder + '/java-tmp' }}"
    state: absent
  register: _result

- name: Create the marker after Java has been unzipped
  ansible.builtin.file:
    path: "{{ wasbld_folder + '/.javaunzipped' }}"
    state: touch
    mode: '0644'
  register: _result
