---

- name: Define remote_user
  ansible.builtin.set_fact:
    remote_user: "{{ hostvars[inventory_hostname].remote_user if (hostvars[inventory_hostname].remote_user is defined) else _remote_user_default }}"
  vars:
    _remote_user_default: "{{ hostvars['cmdline-facts'].cli_remote_user if (hostvars['cmdline-facts'].cli_remote_user | length > 0) else hostvars['localhost-facts'].local_user }}"
