---

- name: Check for undefined remote user when running in a container
  ansible.builtin.assert:
    msg:
      - "You must provide the user for the playbook when running in a container."
      - "e.g. --user root"
    that: not container_run or (options.remote_user | default('') | length > 0) or (hostvars['cmdline-facts'].cli_remote_user | length > 1)

- name: Define remote_user
  ansible.builtin.set_fact:
    options: "{{ options | default({}) | combine({'remote_user': remote_user}) }}"
  vars:
    remote_user_default: "{{ options.remote_user if (options.remote_user | length > 0) else hostvars['localhost-facts'].local_user }}"
    remote_user: "{{ hostvars['cmdline-facts'].cli_remote_user if (hostvars['cmdline-facts'].cli_remote_user | length > 0) else remote_user_default }}"
  when: options.remote_user is not defined or remote_user != options.remote_user
