---

- when: inventory_hostname == (groups['all_nodes'] | first)
  name: Tasks which are only performed on the first VM
  block:

    - name: Remove folders create by install_autowas role
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ hostvars['cluster-facts'].options.autowas_basedir }}"
        - "{{ user_home + '/autowas' }}"
        - "{{ user_home + '/.fyre/stacks' }}"
      register: _result
