---

- name: Get the cluster status
  ansible.builtin.include_role:
    name: gmarcy.ansible.cluster_gather_facts_fyre
    tasks_from: gather_cluster_status.yml

- when: not _cluster_exists
  name: Create the cluster
  block:

    - name: Set distro_include_tasks fact
      ansible.builtin.set_fact:
        _distro_include_tasks: "{{ distro_tasks[kubernetes_distro].provision | default('') }}"

    - name: Assert that we have a tasks file to include
      ansible.builtin.assert:
        that: _distro_include_tasks | length > 0
        msg: "{{ 'Unable to find tasks to include for distro ' + kubernetes_distro }}"

    - name: Include the tasks to create the configuration for the Fyre build operation
      ansible.builtin.include_tasks: "{{ _distro_include_tasks }}"

    - name: Build the cluster and wait for completion
      ansible.builtin.include_tasks: build_cluster_and_wait.yml

- name: Get the cluster details
  ansible.builtin.include_role:
    name: gmarcy.ansible.cluster_gather_facts_fyre
    tasks_from: gather_cluster_details.yml
