---

- name: "{{ 'Add ' + task_to_check + ' to tasks_completed' }}"
  ansible.builtin.set_fact:
    tasks_completed: "{{ _tasks_completed | union([task_to_check]) }}"
  delegate_to: 'playbook-facts'
  delegate_facts: true
  vars:
    _tasks_completed: "{{ hostvars['playbook-facts'].tasks_completed | default([]) }}"
  tags: omit_from_grapher

- name: "{{ 'Stop after ' + task_to_check + ' has completed' }}"
  ansible.builtin.assert:
    that: (stop_after_task | default('')) not in hostvars['playbook-facts'].tasks_completed
    msg: "{{ 'Stopping after ' + (stop_after_task | default('undefined task')) + ' has completed' }}"
  tags: omit_from_grapher
