---

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: cleanup_cluster
  roles:
  - role: gmarcy.ansible.check_stop_before
    task_to_check: task-cleanup-cluster

- name: "{{ 'Cleanup a cluster from ' + hostvars['cluster-facts']['cluster_provisioner'] | default('undefined cluster provisioner') }}"
  hosts: "{{ hostvars['cluster-facts']['cluster_provisioner'] | default('playbook-facts') }}"
  become: false
  gather_facts: false
  tags: cleanup_cluster
  roles:
  - role: gmarcy.ansible.end_current_play
    when: inventory_hostname == 'playbook-facts' or deprovisioning_role is not defined
  - role: gmarcy.ansible.include_dynamic_role
    dynamic_role: "{{ deprovisioning_role }}"

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: cleanup_cluster
  roles:
  - role: gmarcy.ansible.check_stop_after
    task_to_check: task-cleanup-cluster
