---

- name: Prepare Cluster Storage
  hosts: cluster-storage
  gather_facts: false
  tags: cluster_storage
  roles:
  - role: gmarcy.ansible.print_storage_info

- name: "Request storage from {{ hostvars['cluster-storage']['storage_provisioner'] }}"
  hosts: cluster-storage
  gather_facts: false
  tags: cluster_storage
  roles:
  - role: gmarcy.ansible.include_dynamic_role
    dynamic_role: "{{ provisioning_role }}"
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"

- name: Run other cluster-storage roles
  hosts: cluster-storage
  gather_facts: false
  tags: cluster_storage
  roles:
  - role: gmarcy.ansible.set_default_storage_class
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"
  - when: test_storage_provisioner | default(false)
    role: gmarcy.ansible.test_storage_provisioner
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"
