---

- name: Create undefined localhost aliases
  hosts: localhost-facts
  become: false
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: gmarcy.ansible.define_localhost_aliases
    localhost_aliases:
    - 'cluster-facts'

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: gmarcy.ansible.check_stop_before
    task_to_check: task-gather-cluster-facts

- name: Set cluster-facts dependent upon localhost-facts
  hosts: cluster-facts
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: gmarcy.ansible.cluster_facts_init

- name: Determine cluster name
  hosts: cluster-facts
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: gmarcy.ansible.cluster_lookup_name
    when: options.cluster_name is not defined

- name: Load cluster-facts.yaml if is exists
  hosts: cluster-facts
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: gmarcy.ansible.cluster_load_facts

- import_playbook: gmarcy.ansible.gather_cluster_facts_common

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: cluster_facts
  roles:
  - role: gmarcy.ansible.check_stop_after
    task_to_check: task-gather-cluster-facts
