---

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: install_autowas
  roles:
  - role: gmarcy.ansible.check_stop_before
    task_to_check: task-install-autowas

- name: Install AutoWAS
  hosts: all_nodes
  gather_facts: false
  tags: install_autowas
  roles:
  - role: gmarcy.ansible.install_autowas

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: install_autowas
  roles:
  - role: gmarcy.ansible.check_stop_after
    task_to_check: task-install-autowas
