---

- name: Prepare inventory hosts
  hosts: playbook-facts
  gather_facts: false
  pre_tasks:
  - name: This needs to be debugged
    ansible.builtin.fail:
      msg: 'this play is currently broken'
  - name: Check that we have all facts needed for this play
    ansible.builtin.assert:
      that:
      - hostvars['localhost-facts']['ssh_keypair_path'] is defined
      - hostvars['localhost-facts']['ssh_keypair_secret'] is defined
      - groups['inventory_hosts'] is defined
  tasks:
  - when: container_run | bool
    name: Setup ssh keys for container
    block:
    - name: Create ~/.ssh folder if needed
      ansible.builtin.file:
        path: "{{ ssh_keypair_path | dirname }}"
        state: directory
        mode: '0700'
      changed_when: false
    - name: Copy ssh key secret into ~/.ssh when running in a container
      ansible.builtin.copy:
        content: |
          {{ ssh_keypair_key }}
        dest: "{{ ssh_keypair_path }}"
        mode: '0600'
      changed_when: false
    vars:
      ssh_keypair_path: "{{ hostvars['localhost-facts']['ssh_keypair_path'] }}"
      ssh_keypair_secret: "{{ hostvars['localhost-facts']['ssh_keypair_secret'] }}"
      secrets: "{{ hostvars['playbook-secrets'].secrets }}"
      ssh_keypair_key_secret: "{{ secrets[ssh_keypair_secret] }}"
      ssh_keypair_key: "{{ lookup(ssh_keypair_key_secret.module, ssh_keypair_key_secret.param) | trim }}"

- name: Run prepare_host_roles
  hosts: inventory_hosts
  gather_facts: false
  roles:
  - role: gmarcy.ansible.loop_over_roles
    role_loop: "{{ prepare_host_roles }}"
    when: prepare_host_roles is defined
