---

- name: Print cluster information
  hosts: cluster-facts
  gather_facts: false
  tags: cluster_info
  roles:
  - role: gmarcy.ansible.print_cluster_info
    description: "{{ options.cluster_description }}"
