---

- name: "Remove storage from {{ hostvars['cluster-storage']['storage_provisioner'] }}"
  hosts: cluster-storage
  gather_facts: false
  tags: cluster_storage
  roles:
  - role: gmarcy.ansible.include_dynamic_role
    dynamic_role: "{{ deprovisioning_role }}"
    api_key: "{{ hostvars['cluster-facts']['api_key'] | default(omit) }}"
    kubeconfig_path: "{{ hostvars['cluster-facts']['kubeconfig_path'] }}"
