---

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: uninstall_autowas
  roles:
  - role: gmarcy.ansible.check_stop_before
    task_to_check: task-uninstall-autowas

- name: Uninstall AutoWAS
  hosts: all_nodes
  gather_facts: false
  tags: uninstall_autowas
  roles:
  - role: gmarcy.ansible.uninstall_autowas

- name: Check if requested to stop here
  hosts: playbook-facts
  become: false
  gather_facts: false
  tags: uninstall_autowas
  roles:
  - role: gmarcy.ansible.check_stop_after
    task_to_check: task-uninstall-autowas
