---

- name: Set gathering_hosts fact
  ansible.builtin.set_fact:
    gathering_hosts: "{{ groups['all'] | map('extract', hostvars) | selectattr('gathering_roles', 'defined') | map(attribute='inventory_hostname') }}"
