---

artifactory_fqdn:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/artifactory_fqdn' }}"
artifactory_user:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/artifactory_user' }}"
artifactory_identity_token:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/artifactory_identity_token' }}"
