---

fyre_user:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/fyre_user' }}"
fyre_user_email:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/fyre_user_email' }}"
fyre_apikey:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/fyre_apikey' }}"
