---

ghapi_app_app_id:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/ghapi_app_app_id' }}"
ghapi_app_client_id:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/ghapi_app_client_id' }}"
ghapi_app_client_secret:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/ghapi_app_client_secret' }}"
ghapi_app_private_key:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/ghapi_app_private_key' }}"
