---

w3id_username:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/w3id_username' }}"
w3id_password:
  module: 'ansible.builtin.unvault'
  param: "{{ secrets_dir + '/w3id_password' }}"
